### ISSUE TITLE
元に戻すを押したら一瞬光った枠がウインドウから外れます

### ISSUE THREAD

**Issue by 2ji3150** [Grabacr07/MetroRadiance#27]
最大化の状態で元に戻す(縮小)を押すと
光った枠がウインドウから外れて､先に縮小したように見えます｡
Visual Studioを見てみるとこれは起こりません｡
多分元に戻すまで一旦光をオフにした方が見栄がいいと思います｡

**Comment by Grabacr07** [comment]
私の手元では再現しない動作です。
できれば、再現手順や更に詳細な再現環境、実際の動作の様子等詳しい情報を頂けると助かります。

**Comment by Heiseikiseki** [comment]
(日本語あんまり上手ではないのですみません)
実際の動作の様子の録画です(GIF)
よく見たら最大化をするときも最大化する最中にウインドウの光った枠が残っている一瞬が見えます｡



https://www.dropbox.com/s/fgv3qohbr23ond7/%E9%8C%B2%E7%94%BB_2016_05_12_02_03_02_337.gif?dl=1
いかがでしょうか?

**Comment by Grabacr07** [comment]
状況は把握しました。ありがとうございます。

VM 上での動作でしょうか？ (最大化 ｰ> 通常へ戻したときに、ウィンドウの位置が納まるまで時間がかかっているように見えたため)
OS 等の環境情報も頂ければ、こちらで再現するか確認してみます。

**Comment by Heiseikiseki** [comment]
いいえ､
Windows 10 Pro正式版です｡
Intel I7-4510U+8GRAM

多分だと思いますが
そちらが再現できないのはアニメーションをオフしてるかと｡
http://i.imgur.com/J6Z8JDX.jpg

**Comment by Grabacr07** [comment]
いえ、Windows 10 Pro/Enterpirse でこちらも同様の設定です。
![ss160512152159ls](https://cloud.githubusercontent.com/assets/1779073/15205793/4ff15b68-1855-11e6-8337-57b441773e15.png)

こちらの手元でアニメーションが有効になっているすべての Windows 10 環境で、まだ再現していません。
ただ、アニメーションの効果時間が違う可能性はありますね。
